//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_ogrenci_ogretmen.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class notlar
    {
        public int notID { get; set; }
        public Nullable<short> sinav1 { get; set; }
        public Nullable<short> sinav2 { get; set; }
        public Nullable<short> sozlu1 { get; set; }
        public Nullable<short> sozlu2 { get; set; }
        public Nullable<short> proje { get; set; }
        public Nullable<int> ders { get; set; }
        public Nullable<int> ogrenci { get; set; }
        public Nullable<double> donemSonuNotu { get; set; }
    
        public virtual ders ders1 { get; set; }
        public virtual ogrenci ogrenci1 { get; set; }
    }
}
