//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_ogrenci_ogretmen.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrenci()
        {
            this.notlar = new HashSet<notlar>();
        }
    
        public int ogrID { get; set; }
        public string ogr_isim { get; set; }
        public string ogr_soyisim { get; set; }
        public string ogr_no { get; set; }
        public string ogr_sifre { get; set; }
        public string ogr_mail { get; set; }
        public Nullable<int> ogr_sinif { get; set; }
        public string ogr_foto { get; set; }
        public Nullable<bool> ogr_durum { get; set; }
    
        public virtual sinif sinif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notlar> notlar { get; set; }
    }
}
